# Generated by Django 6.0 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
