# Generated by Django 6.0 on 2025-12-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_details'),
        ),
    ]
