# Generated by Django 6.0 on 2025-12-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_issue_reported_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='UserDetails',
        ),
    ]
