# Generated by Django 6.0 on 2025-12-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_details_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='reported_by',
            new_name='reported_by_id',
        ),
    ]
