# Generated by Django 6.0 on 2025-12-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sitenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenotification',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.issue'),
        ),
    ]
