# Generated by Django 6.0 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sitenotification_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
