# Generated by Django 6.0 on 2025-12-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userdetails_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('suggested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Suggested', max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='app.issue')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
        ),
    ]
