# Generated by Django 6.0 on 2025-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_solutions', to='app.userdetails'),
        ),
    ]
