# Generated by Django 6.0 on 2025-12-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_solution_voted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='voted_by',
        ),
    ]
