# Generated by Django 5.2.8 on 2025-12-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_solution_voted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_solutions', to='app.userdetails'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
