# Generated by Django 5.2.8 on 2025-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_solution_voted_by_alter_solution_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
