# Generated by Django 5.2.8 on 2025-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_voting_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
