# Generated by Django 6.0 on 2025-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_solution_is_voting_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
