# Generated by Django 6.0 on 2025-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_solution_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
