# Generated by Django 6.0 on 2025-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_solution_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
