# Generated by Django 6.0 on 2025-12-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_solution_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userdetails'),
        ),
    ]
